name: 'ra_data_warehouse'
version: '0.0.2'

profile: 'ra_data_warehouse'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

on-run-start:
    - "create table if not exists {{ generate_prefixed_target_name() }}_logs.audit_dbt_results (object string, status string, row_count numeric, execution_time numeric, load_ts timestamp)"

on-run-end:
    - "insert into {{ generate_prefixed_target_name() }}_logs.audit_dbt_results (object, status, row_count, execution_time, load_ts) values {{ results_values(results) }}"

models:
  ra_data_warehouse:
# source adapter general settings
      sources:
          materialized: view
          schema: staging
# source adapter module settings
          stg_asana_projects:
              vars:
                  id-prefix: asana-
                  staff_email_domain: example.com
                  workspaces_table: #schema.workspaces
                  projects_table: #schema.projects
                  tasks_table: #schema.tasks
                  users_table: #schema.users
          stg_facebook_ads:
              vars:
                  id-prefix: fbads-
                  adcreative_table: #schema.adcreative
                  ads_table: #schema.ads
                  adsets_table: #schema.adsets
                  campaigns_table: #schema.campaigns
                  ads_insights_age_and_gender_table: #schema.ads_insights_age_and_gender
                  ads_insights_table: #schema.ads_insights
          stg_google_ads:
              vars:
                  id-prefix: gads-
                  accounts_table: #schema.accounts
                  campaigns_table: #schema.campaigns
          stg_harvest_projects:
              vars:
                  id-prefix: harvest-
                  staff_email_domain: example.com
                  clients_table: #schema.clients
                  contacts_table: #schema.contacts
                  invoices_table: #schema.invoices
                  invoice_line_items_table: #schema.invoice_line_items
                  projects_table: #schema.projects
                  tasks_table: #schema.tasks
                  project_tasks_table: #schema.project_tasks
                  time_entries_table: #schema.time_entries
                  users_table: #schema.users
                  user_projects_table: #schema.user_projects
                  user_project_tasks_table: #schema.user_project_tasks
                  expenses_table: #schema.expenses
          stg_hubspot_crm:
              vars:
                  id-prefix: hubspot-
                  etl: stitch
                  stitch_companies_table: #schema.companies
                  stitch_contacts_table: #schema.contacts
                  stitch_deals_table: #schema.deals
                  stitch_owners_table: #schema.owners
                  stitch_pipeline_stages_table: #schema.pipeline_stages
                  stitch_deal_pipelines_table: #schema.deal_pipelines
                  fivetran_company_table: #schema.company
                  fivetran_contact_table: #schema.contact
                  fivetran_deal_table: #schema.deal
                  fivetran_owner_table: #schema.owner
                  fivetran_pipeline_stage_table: #schema.pipeline_stage
                  fivetran_pipeline_table: #schema.pipeline
                  fivetran_property_history_table: #schema.property_history
                  fivetran_deal_company_table: #schema.deal_company
          stg_intercom_messaging:
              vars:
                  id-prefix: intercom-
                  stitch_contacts_table: #schema.contacts
                  stitch_conversations_table: #schema.conversations
          stg_jira_projects:
              vars:
                  id-prefix: jira-
                  staff_email_domain: example.com
                  stitch_projects_table: #schema.projects
                  stitch_project_types_table: #schema.project_types
                  stitch_project_categories_table: #schema.project_categories
                  stitch_issues_table: #schema.issues
                  stitch_users_table: #schema.users
          stg_mailchimp_email:
              vars:
                  id-prefix: mailchimp-
                  stitch_list_members_table: #schema.list_members
                  stitch_reports_email_activity_table: #schema.reports_email_activity
                  stitch_lists_table: #schema.lists
                  stitch_campaigns_table: #schema.campaigns
          stg_mixpanel_events:
              vars:
                  id-prefix: mixpanel-
                  etl: fivetran
                  fivetran_event_table: #schema.event
                  stitch_export_table: #schema.export
          stg_segment_events:
              vars:
                  id-prefix: segment-
                  tracks_table: #schema.tracks
                  pages_table: #schema.pages
          stg_stripe_payments:
              vars:
                  id-prefix: stripe-
                  stitch_balance_transactions_table: #schema.balance_transactions
                  stitch_charges_table: #schema.charges
                  stitch_events_table: #schema.events
                  stitch_payout_transactions_table: #schema.payout_transactions
                  stitch_payouts_table: #schema.payouts
          stg_xero_accounting:
              vars:
                  id-prefix: xero-
                  stitch_accounts_table: #schema.accounts
                  stitch_categories_table: #schema.tracking_categories
                  stitch_bank_transactions_table: #schema.bank_transactions
                  stitch_contacts_table: #schema.contacts
                  stitch_currencies_table: #schema.currencies
                  stitch_expense_claims_table: #schema.expense_claims
                  stitch_invoices_table: #schema.invoices
                  stitch_payments_table: #schema.payments
# integration layer settings
      integration:
          materialized: view
          schema: staging
          vars:
              web_sessionization_trailing_window: 3
              web_inactivity_cutoff: 30 * 60
# warehouse layer settings
      warehouse:
          materialized: table
# util module settings
      utils:
          materialized: view
          schema: logs
# source adapter enable/disable settings
  vars:
      enable_harvest_projects_source:      false
      enable_hubspot_crm_source:           false
      hubspot_crm_source_type:             stitch
      enable_asana_projects_source:        false
      enable_jira_projects_source:         false
      enable_stripe_payments_source:       false
      enable_xero_accounting_source:       false
      enable_mailchimp_email_source:       false
      enable_segment_events_source:        false
      enable_google_ads_source:            false
      enable_facebook_ads_source:          false
      enable_intercom_messaging_source:    false
      enable_custom_source_1:              false
      enable_custom_source_2:              false
      enable_mixpanel_events_source:       false
      mixpanel_events_source_type:         fivetran
# warehouse modules
      enable_crm_warehouse:         false
      enable_finance_warehouse:     false
      enable_projects_warehouse:    false
      enable_marketing_warehouse:   false
      enable_ads_warehouse:         false
      enable_product_warehouse:     false




seeds:
  ra_data_warehouse:
    schema: seed
