version:  2

models:
  - name: stg_hubspot_crm_contacts
    description: "Hubspot Contacts Dimension Staging"
    columns:
      - name: contact_id
        tests:
          - unique
          - not_null
      - name: contact_created_date
        tests:
          - not_null
  - name: stg_hubspot_crm_companies
    columns:
      - name: hubspot_company_id
        description: This is a unique identifier for the customer within HubSpot
        tests:
          - not_null
          - unique
  - name: stg_hubspot_crm_deals
    columns:
      - name: hubspot_company_id
        description: This is a unique identifier for the customer within HubSpot
        tests:
          - not_null
          - unique
      - name: deal_stage_label
        tests:
          - not_null
      - name: deal_delivery_start_ts
        tests:
          - not_null
      - name: hubspot_company_name
        description: This is a unique identifier for the customer within HubSpot
        tests:
          - not_null
          - unique
      - name: deal_delivery_schedule_ts
        tests:
          - not_null
      - name: hubspot_company_name
        description: This is a unique identifier for the customer within HubSpot
        tests:
          - not_null
          - unique
      - name: deal_number_of_sprints
        tests:
          - not_null
  - name: stg_hubspot_crm_pipelines
    columns:
      - name: pipelineid
        description: This is a unique identifier for the pipe line
        tests:
          - unique
          - not_null
  - name: stg_hubspot_crm_pipeline_stages
    columns:
      - name: stageid
        description: This is a unique identifier for the pipe line
        tests:
          - unique
          - not_null
  - name: stg_hubspot_crm_owners
    columns:
      - name: ownerid
        description: HubSpot uses owners to assign CRM objects (contacts, companies, and deals) to specific people in your organization.
